import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { geoOrthographic, geoPath, geoGraticule, geoEquirectangular } from 'd3-geo';
import { feature } from 'topojson-client';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..', '..');
const W = 1000;

const isoLatam = new Set<number>([
  32, 68, 76, 152, 170, 188, 192, 214, 218, 222, 320, 328, 332, 340, 388,
  484, 558, 591, 600, 604, 740, 780, 858, 862,
]);

const isoAfrica = new Set<number>([
  12, 24, 72, 86, 108, 120, 132, 140, 148, 174, 175, 178, 180, 204, 226, 231, 232,
  262, 266, 270, 288, 324, 384, 404, 426, 430, 434, 450, 454, 466, 478, 480, 504,
  508, 516, 562, 566, 624, 646, 654, 686, 690, 694, 706, 710, 716, 728, 729, 732,
  748, 768, 788, 800, 818, 834, 854,
]);

const isoAsia = new Set<number>([
  // South Asia + SE Asia + Pacific + Middle East + Mongolia/NK
  4, 50, 64, 144, 356, 462, 524, 586,
  104, 116, 360, 418, 458, 608, 626, 702, 704, 764,
  90, 242, 296, 540, 548, 584, 585, 598, 776, 798, 882,
  368, 376, 400, 414, 422, 512, 760, 784, 887,
  408, 496,
]);

const globalSouthIso = new Set<number>([...isoLatam, ...isoAfrica, ...isoAsia]);

async function main() {
  const topoBuf = await readFile(path.join(ROOT, 'node_modules', 'world-atlas', 'countries-110m.json'));
  const topo: any = JSON.parse(topoBuf.toString('utf8'));
  const countries: any = feature(topo, topo.objects.countries);
  const allLand: any[] = countries.features;

  const buildAt = (lon: number, lat: number) => {
    const proj = geoOrthographic()
      .scale(W / 2 - 2)
      .translate([W / 2, W / 2])
      .clipAngle(90)
      .rotate([lon, lat]);
    return geoPath(proj);
  };

  // Per-rotation paths (sphere stays identical across rotations, so compute once)
  const sphere = buildAt(0, 0)({ type: 'Sphere' } as any) ?? '';

  const computeFrame = (lon: number, lat: number) => {
    const pathGen = buildAt(lon, lat);
    const graticule = geoGraticule().step([20, 20]);
    const grat = pathGen(graticule() as any) ?? '';
    const all = allLand
      .map((f: any) => pathGen(f))
      .filter((d: any) => d)
      .join(' ');
    const pathFor = (iso: Set<number>) => allLand
      .filter((f: any) => iso.has(+f.id))
      .map((f: any) => pathGen(f))
      .filter((d: any) => d)
      .join(' ');
    return {
      g: grat,
      a: all,
      l: pathFor(isoLatam),
      f: pathFor(isoAfrica),
      s: pathFor(isoAsia),
    };
  };

  // Static still: rotation centered on LATAM (around Ecuador/Colombia)
  // rotate([λ, φ]) puts the point at (-λ, -φ) at the projection center.
  // (-75, -5) is central LATAM; Mexico through Argentina visible, West Africa peeks at right edge.
  const stillLon = 75;
  const stillLat = 5;
  const still = computeFrame(stillLon, stillLat);
  const gsStill = allLand
    .filter((f: any) => globalSouthIso.has(+f.id))
    .map((f: any) => buildAt(stillLon, stillLat)(f))
    .filter((d: any) => d)
    .join(' ');

  // Animation frames: 12 frames covering 360° at 30° steps, slight tilt
  const N_FRAMES = 12;
  const TILT = -10;
  // Start at lon=80 (LATAM coming into view from the right), rotate east-to-west by decrementing.
  // d3 geoOrthographic.rotate([lon,lat]) — increasing lon rotates the globe westward (Earth spins east).
  // To make the globe appear to spin to the right (so continents move L→R), increase lon each frame.
  const frames = [] as ReturnType<typeof computeFrame>[];
  for (let i = 0; i < N_FRAMES; i++) {
    const lon = (i * 360) / N_FRAMES; // 0, 30, 60, ..., 330
    frames.push(computeFrame(lon, TILT));
  }

  // Flat-in-circle variant: equirectangular projection cropped to a circle.
  // Lets us show LATAM + Africa + Asia simultaneously — orthographic can only show ~180° of arc.
  const flatProj = geoEquirectangular()
    .scale(W / (2 * Math.PI))
    .translate([W / 2, W / 2]);
  const flatPath = geoPath(flatProj);
  const flatPathFor = (iso: Set<number>) => allLand
    .filter((f: any) => iso.has(+f.id))
    .map((f: any) => flatPath(f))
    .filter((d: any) => d)
    .join(' ');
  const flatAll = allLand
    .map((f: any) => flatPath(f))
    .filter((d: any) => d)
    .join(' ');
  const flatLatam = flatPathFor(isoLatam);
  const flatAfrica = flatPathFor(isoAfrica);
  const flatAsia = flatPathFor(isoAsia);

  const out: string[] = [];
  out.push(`// auto-generated by _precompute-globe.ts — orthographic + equirectangular projections, W=${W}`);
  out.push(`// still: rotate(${stillLon},${stillLat}); frames: ${N_FRAMES} × 30° at tilt ${TILT}; flat: equirectangular fit-to-width`);
  out.push(`export const GLOBE_VIEWBOX = ${W};`);
  out.push(`export const GLOBE_SPHERE_PATH = ${JSON.stringify(sphere)};`);
  out.push(`export const GLOBE_GRATICULE_PATH = ${JSON.stringify(still.g)};`);
  out.push(`export const GLOBE_ALL_LAND_PATH = ${JSON.stringify(still.a)};`);
  out.push(`export const GLOBE_GLOBAL_SOUTH_PATH = ${JSON.stringify(gsStill)};`);
  out.push(`export const GLOBE_REGION_LATAM_PATH = ${JSON.stringify(still.l)};`);
  out.push(`export const GLOBE_REGION_AFRICA_PATH = ${JSON.stringify(still.f)};`);
  out.push(`export const GLOBE_REGION_ASIA_PATH = ${JSON.stringify(still.s)};`);
  out.push(``);
  out.push(`export const GLOBE_FLAT_ALL_LAND_PATH = ${JSON.stringify(flatAll)};`);
  out.push(`export const GLOBE_FLAT_LATAM_PATH = ${JSON.stringify(flatLatam)};`);
  out.push(`export const GLOBE_FLAT_AFRICA_PATH = ${JSON.stringify(flatAfrica)};`);
  out.push(`export const GLOBE_FLAT_ASIA_PATH = ${JSON.stringify(flatAsia)};`);
  out.push(``);
  out.push(`export interface GlobeFrame {`);
  out.push(`  graticule: string;`);
  out.push(`  allLand: string;`);
  out.push(`  latam: string;`);
  out.push(`  africa: string;`);
  out.push(`  asia: string;`);
  out.push(`}`);
  out.push(``);
  out.push(`export const GLOBE_FRAMES: GlobeFrame[] = [`);
  for (const fr of frames) {
    out.push(`  { graticule: ${JSON.stringify(fr.g)}, allLand: ${JSON.stringify(fr.a)}, latam: ${JSON.stringify(fr.l)}, africa: ${JSON.stringify(fr.f)}, asia: ${JSON.stringify(fr.s)} },`);
  }
  out.push(`];`);

  process.stdout.write(out.join('\n') + '\n');
}

main().catch((e) => { console.error(e); process.exit(1); });
