import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { geoEquirectangular, geoContains } from 'd3-geo';
import { feature } from 'topojson-client';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..', '..');

// Canvas: 1200 wide × 720 tall, equirectangular. We'll scale at render time via CSS.
const W = 1200;
const H = 720;
const COLOR_PRIMARY = '#1F4D32';   // AISC forest (calm land, on cream bg)
const COLOR_GLOW = '#E5604D';      // AISC coral (LATAM hotspots)

// Dot grid step (px). Smaller = denser map. Apart uses ~10-14px spacing.
const STEP = 10;

// Latam ISO numeric codes — these get the yellow "hotspot" treatment
const isoLatam = new Set<number>([
  32, 68, 76, 152, 170, 188, 192, 214, 218, 222, 320, 328, 332, 340, 388,
  484, 558, 591, 600, 604, 740, 780, 858, 862,
]);

async function main() {
  const topoBuf = await readFile(path.join(ROOT, 'node_modules', 'world-atlas', 'countries-110m.json'));
  const topo: any = JSON.parse(topoBuf.toString('utf8'));
  const countries: any = feature(topo, topo.objects.countries);
  const allLand: any[] = countries.features;

  const latamFeatures = allLand.filter((f: any) => isoLatam.has(+f.id));

  // Equirectangular projection: cover the canvas exactly
  const proj = geoEquirectangular()
    .scale(W / (2 * Math.PI))
    .translate([W / 2, H / 2]);

  const projInv = proj.invert!;

  // Helper: is a point on land?
  const isLand = (lng: number, lat: number) => {
    for (const f of allLand) {
      if (geoContains(f, [lng, lat])) return true;
    }
    return false;
  };
  const isLatam = (lng: number, lat: number) => {
    for (const f of latamFeatures) {
      if (geoContains(f, [lng, lat])) return true;
    }
    return false;
  };

  // Iterate canvas grid, project each point to lng/lat, test land containment
  const dotsLand: Array<[number, number]> = [];
  const dotsLatam: Array<[number, number]> = [];
  for (let y = 0; y < H; y += STEP) {
    for (let x = 0; x < W; x += STEP) {
      const lnglat = projInv([x, y]) as [number, number];
      if (!lnglat) continue;
      const [lng, lat] = lnglat;
      if (lat > 84 || lat < -60) continue; // skip polar regions for cleaner look
      if (isLand(lng, lat)) {
        if (isLatam(lng, lat)) dotsLatam.push([x, y]);
        else dotsLand.push([x, y]);
      }
    }
  }

  const r = STEP * 0.20; // dot radius — small enough to feel like pixels, not coverage
  const rLatam = STEP * 0.32; // slight emphasis on home region

  const circles = [
    ...dotsLand.map(([x, y]) => `<circle cx="${x}" cy="${y}" r="${r}" fill="${COLOR_PRIMARY}" opacity="0.78"/>`),
    ...dotsLatam.map(([x, y]) => `<circle cx="${x}" cy="${y}" r="${rLatam}" fill="${COLOR_GLOW}" opacity="0.95"/>`),
  ].join('');

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">${circles}</svg>`;

  const outSvg = path.join(HERE, '_world-dots.svg');
  await writeFile(outSvg, svg);

  // Also write a TS module exporting a base64 data URL for easy import
  const dataUrl = `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`;
  const outTs = path.join(HERE, '_world-dots-data.ts');
  const tsBody = `// auto-generated by _precompute-world-dots.ts\n// ${dotsLand.length} land dots + ${dotsLatam.length} latam dots, ${W}×${H} equirectangular, step ${STEP}px\nexport const WORLD_DOTS_W = ${W};\nexport const WORLD_DOTS_H = ${H};\nexport const WORLD_DOTS_DATAURL = ${JSON.stringify(dataUrl)};\n`;
  await writeFile(outTs, tsBody);

  console.log(`✓ ${dotsLand.length} land dots + ${dotsLatam.length} latam dots`);
  console.log(`  SVG: ${outSvg} (${(svg.length / 1024).toFixed(0)} KB)`);
  console.log(`  TS:  ${outTs}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
